### ISSUE TITLE
Loading the extension locally no longer works for me

### ISSUE THREAD

**Issue by tobywhughes** [kpey/SnapzuEnhancement#21]
The version on the chrome store works for me, but I can't quite figure out how to get the extension to work with my local repo anymore. Seems the process has changed and I know very little about chrome extensions. Getting this error:

    Failed to load extension from: D:\github\SnapzuEnhancement\SnapzuEnhancement\chrome
    Could not load extension icon 'lib/images/logo-32.png'.

This is using the same method I used before.

**Comment by kpey** [comment]
Sorry, I should've written up a how-to when the format got changed. Instead of having two copies of the library (one for chrome, one for FF), the code has been rearranged:

```
lib/
    - core/
        - utils.js, init.js, etc.
    - modules/
        - nightMode.js, etc.
    - images/
        - logo-32.png, etc.
    - css/
        - nightmode.css, etc.
chrome/
    - html/
        - popup.html, etc.
firefox/
    - data/
        - firefox.js
    - lib/
        - main.js
```
If you want things to be nice and easy, you should install [grunt](http://gruntjs.com/) to automatically copy files from the base ```lib``` folder into the two browser locations. Chrome will copy into ```chrome/lib``` and Firefox will copy into ```firefox/data/lib```.

If you want to do this manually, simply copy the ```SnapzuEnhancement/lib``` folder into ```SnapzuEnhancement/chrome``` and the extension will work.
