### ISSUE TITLE
Text looks bad and clips in some places with nightmode

### ISSUE THREAD

**Issue by kpey** [kpey/SnapzuEnhancement#9]
Font and sizing needs to be reverted to what the site has already.

**Comment by logomaster256** [comment]
Bug:
![2015-07-14--1436884114_1468x327_scrot](https://cloud.githubusercontent.com/assets/3049847/8675646/7a8f4762-2a45-11e5-8c3e-b931c644e504.png)

Steps to reproduce it:
 * Visit a snap like http://snapzu.com/hiihii/north-korea-invites-us-congress-to-visit-alleged-anthrax-plant and scroll down to the "Here are some other snaps you may like..."

Additional info: when you hover over it, the background for the text turns to grey so you can read it (since the text colour is white).

**Comment by kpey** [comment]
![](http://i.imgur.com/sSMzEAq.png)

![](http://i.imgur.com/ARmvXN7.png)


I'm not seeing this so it seems I fixed it when trying to fix another issue. Probably related to nightmode.css line 81-88 (.photo, p).

**Comment by logomaster256** [comment]
Yay, works! 
![2015-07-14--1436885834_1457x301_scrot](https://cloud.githubusercontent.com/assets/3049847/8676377/6ce62564-2a49-11e5-9104-8c4b1b3a1c7f.png)
But it doesn't change on hover (just to make sure it's intentional).

**Comment by kpey** [comment]
I'm not really sure it has to change as the mouse pointer should be enough feedback for the user. Might just keep it as is for now.
